[project]
name = "learn-complete-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=8.31.0",
    "nest-asyncio>=1.6.0",
]
